services:
  database:
    container_name: mysqldb
    platform: linux/x86_64
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
